# Generated by Django 4.2.30 on 2026-06-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=100)),
                ('menu_link', models.CharField(max_length=255)),
                ('menu_position', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['menu_position'],
            },
        ),
    ]
