# Generated by Django 4.2.30 on 2026-06-10 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=255)),
                ('menu_link', models.CharField(max_length=255)),
                ('submenu', models.CharField(max_length=255)),
                ('position', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.main_menu')),
            ],
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
