# Generated by Django 4.2.30 on 2026-06-10 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_main_menu_delete_menu'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Main_menu',
            new_name='Main_menuss',
        ),
    ]
