# Generated by Django 4.2.30 on 2026-06-12 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_menuss',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounts.main_menuss'),
        ),
        migrations.AlterField(
            model_name='services',
            name='menu',
            field=models.ForeignKey(db_column='menu_id', on_delete=django.db.models.deletion.CASCADE, related_name='service', to='accounts.main_menuss'),
        ),
    ]
