# Generated by Django 4.2.30 on 2026-06-12 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_service_alter_main_menuss_parent_delete_services_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
