# Generated by Django 4.2.30 on 2026-06-12 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
